/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'merose' at '7/26/17 2:15 PM' with Gradle 2.0
 *
 * @author merose, @date 7/26/17 2:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
